# Generated by Django 5.0.3 on 2024-03-10 06:14

import apps.core.models
import django.db.models.deletion
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True, validators=[apps.core.models.Profile.validate_date], verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], default='male', verbose_name='Gender')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, validators=[apps.core.models.Profile.validate_date], verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, validators=[apps.core.models.Profile.validate_date], verbose_name='Updated At')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('first_release_year', models.IntegerField(blank=True, null=True, verbose_name='First Release Year')),
                ('no_of_albums_released', models.IntegerField(blank=True, null=True, verbose_name='Number of Albums Released')),
            ],
            options={
                'verbose_name': 'Artist Profile',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True, validators=[apps.core.models.Profile.validate_date], verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], default='male', verbose_name='Gender')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, validators=[apps.core.models.Profile.validate_date], verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, validators=[apps.core.models.Profile.validate_date], verbose_name='Updated At')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
    ]
