# Generated by Django 5.0.3 on 2024-03-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_artistprofile_id_musicartists_artistprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='artists',
            field=models.ManyToManyField(related_name='musics', through='core.MusicArtists', to='core.artistprofile'),
        ),
    ]
